#!/usr/bin/env bash

# Define variables
private_key_name="school"
key_bits=4096
passphrase="betty"

# Generate RSA key pair
ssh-keygen -t rsa -b "$key_bits" -N "$passphrase" -f "$private_key_name"

echo "RSA key pair created:"
echo "Private key: ${private_key_name}"
echo "Public key: ${private_key_name}.pub"
